const { SNOWPACK_PUBLIC_MAPBOXGL_ACCESS_TOKEN, SNOWPACK_PUBLIC_DATA_URL, SNOWPACK_PUBLIC_TRANSLATION_URL} = import.meta.env


export default {
  dataUrl: SNOWPACK_PUBLIC_DATA_URL,
  accessToken: SNOWPACK_PUBLIC_MAPBOXGL_ACCESS_TOKEN,
  translationUrl: SNOWPACK_PUBLIC_TRANSLATION_URL
}
